spring:
  datasource:
    hikari:
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul
      hibernate.id.new_generator_mappings: true
#      hibernate.connection.provider_disables_autocommit: true
      # hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  task:
    execution:
      thread-name-prefix: factsheet-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: factsheet-scheduling-
      pool:
        size: 2
  sql:
    init:
      schema-locations:
        classpath*:sql/common/schema.sql,
        classpath*:sql/common/alteration.sql,
        classpath*:sql/common/common_code.sql
      mode: always

server:
  servlet:
    session:
      cookie:
        http-only: true
  version: 1.0.0
  port: 8080

logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}:%-3relative]  %clr(%-5level) %clr(${PID:-}){magenta} %clr(---){faint} %clr([%15.15thread]){faint} %clr(%-40.40logger{36}){cyan} %clr(:){faint} %msg%n"
  level:
    root: INFO
    org.hibernate.SQL: WARN
#    org.springframework.web: TRACE
#    org.springframework.web.servlet.handler.HandlerMappingIntrospector: ERROR
